### PR TITLE
cram cram

### LINKED ISSUE #178: Refactor ALL XML Files
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Issue to be done last, final refactoring issue for ensuring our UI looks exactly as we want it to (or match it to be as close as possible to as to how we have our mockups). 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 8

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### LINKED ISSUE #187: Finalize Documentation
Description: Issue for finalizing and updating:
- JavaDocs
- Wiki
- UML
- Mockups
- Resources

Story Points: 13

### LINKED ISSUE #189: Restructure Project Folder
Description: Restructure project folder since everything is just in the `src` folder and not very organized

Story Points: 1

### PR DESCRIPTION
**Pull request by raysarinas**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description: 👎 

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)

[//]: # (automatically closes given issue number)
Closes #178 
Closes #187 
Closes #189

### CODE REVIEW

File: app/src/androidTest/java/com/example/vybe/Helpers/SwipeView.java [hunk 1]
```diff
@@ -18,4 +18,6 @@ public static ViewAction LeftSwipe() {
                 GeneralLocation.CENTER_RIGHT, Press.FINGER);
     }
 
+
+
```
Comment (jacobwong98) [inline app/src/androidTest/java/com/example/vybe/Helpers/SwipeView.java]: sure

File: app/src/androidTest/java/com/example/vybe/MapFragmentTest.java [hunk 2]
```diff
@@ -94,33 +98,66 @@ private void LogIntoActivity() throws InterruptedException {
...
         onView(withText("Select a Vibe")).check(matches(isDisplayed()));
 
-        onView(withId(R.id.carousel_picker)).perform(RightSwipe());
-        Thread.sleep(1000);
-        onView(withId(R.id.carousel_picker)).perform(RightSwipe());
-        Thread.sleep(1000);
+//        onView(withId(R.id.carousel_picker)).perform(RightSwipe());
+//        Thread.sleep(1000);
+//        onView(withId(R.id.carousel_picker)).perform(RightSwipe());
+//        Thread.sleep(1000);
```
Comment (jacobwong98) [inline app/src/androidTest/java/com/example/vybe/MapFragmentTest.java]: ok

File: app/src/androidTest/java/com/example/vybe/MapFragmentTest.java [hunk 3]
```diff
@@ -130,6 +167,9 @@ public void Test01_AddVibeWithLocation() throws InterruptedException, UiObjectNo
         onView(withId(R.id.btn_current_location)).perform(click());
         Thread.sleep(2000);
 
+        //swipe to bottom
+//        onView(withId(R.id.image_view)).perform(swipeUp());
+
```
Comment (jacobwong98) [inline app/src/androidTest/java/com/example/vybe/MapFragmentTest.java]: plz remove

File: app/src/androidTest/java/com/example/vybe/MapFragmentTest.java [hunk 4]
```diff
@@ -176,11 +250,23 @@ public void Test02_DisplayMapFragment() throws InterruptedException, UiObjectNot
...
     @After
     public void Exit() {
-        mAuth.getInstance().signOut();
+
+        onView(withId(R.id.profile_btn)).perform(click());
+
+//        Thread.sleep(1000);
+
+        // Confirm profile information is correct
+        //onView(withId(R.id.email_profile)).check(matches(withText(containsString(latteEmail))));
```
Comment (jacobwong98) [inline app/src/androidTest/java/com/example/vybe/MapFragmentTest.java]: delete

File: app/src/main/java/com/example/vybe/Models/VibeEvent.java [hunk 5]
```diff
@@ -158,6 +158,10 @@ public void setSocSit(String socSit) {
      */
     public void setImage(String image) { this.image = image; }
 
+    /**
+     * This
+     * @return
+     */
     public Double getLatitude() {
```
Comment (jacobwong98) [inline app/src/main/java/com/example/vybe/Models/VibeEvent.java]: excuse what is this

**Review by jacobwong98 — DISMISSED** [review]

**Review by jacobwong98 — APPROVED** [review]
thxs
