### PR TITLE
Fixed ListView resetting after returning from another acitivity

### LINKED ISSUE #179: Fix Filtering Reset When Leaving Page
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: BUG

[//]: # (Please Add labels for type of issue)

Description: When you filter and then click on "Add" or just like leave the page, the filtering is undone but the description in the filter remains filtered. 

This issue may be related to Issue #132 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 5

Related Issues: N/A

Example of Bug after filtering for "Happy" then trying to add and returning to MyVibesActivity
Screenshot_1574671756

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### PR DESCRIPTION
**Pull request by jacobwong98**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description: ListView was "resetting" the vibes history by bringing in the default list of vibes (all vibes). Changed it so it should retain the previous filter when returning from another activity

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)

[//]: # (automatically closes given issue number)
Closes #179   

Proof of Concept

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

Checklist

[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is **properly commented**
- [x] Code changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/com/example/vybe/MyVibesActivity.java [hunk 1]
```diff
@@ -119,47 +118,10 @@ public void onClick(View v) {
...
-                                            }
-                                        }
-                                    }
-                                    myVibesAdapter.notifyDataSetChanged();
-                                }
-                            });
+                filterVibe = vibes[position];
+                allFlag = true;
+                if (position != 0){ allFlag = false;}
+                getVibeHistory(filterVibe);
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MyVibesActivity.java]: oooo she clean 🥵

File: app/src/main/java/com/example/vybe/MyVibesActivity.java [hunk 2]
```diff
@@ -345,4 +285,42 @@ private void buildRecyclerView() {
         DividerItemDecoration itemDecor = new DividerItemDecoration(this, DividerItemDecoration.VERTICAL);
         vibesRecyclerView.addItemDecoration(itemDecor);
     }
+
+    public void getVibeHistory(String vibeFilter){
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MyVibesActivity.java]: this will prob be moved to a controller? yea
