### PR TITLE
Moved query to onStart to fix bug

### LINKED ISSUE #142: ListView Not Updating After Add
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Defect/Bug. ListView for Personal Vibe Event History is not automatically updating when adding a new Vibe Event. 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 3

Related Issues: N/A

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### PR DESCRIPTION
**Pull request by jacobwong98**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description: 

ListView was not calling the query after returning from AddEditVibeActivity because of the Activity lifecycle. I moved it onto onStart() so that the query is always called instead of only once in onCreate

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)

[//]: # (automatically closes given issue number)
Closes #142   

Proof of Concept

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

Checklist

[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is **properly commented**
- [x] Code changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/com/example/vybe/MyVibesActivity.java [hunk 1]
```diff
@@ -273,6 +233,48 @@ public void onClick(View v) {
...
+
+        query.get().addOnSuccessListener((QuerySnapshot queryDocumentSnapshots) -> {
+                vibeEventList.clear();
+                for (QueryDocumentSnapshot doc : queryDocumentSnapshots) {
+//                    LocalDateTime ldt = LocalDateTime.ofInstant(Instant.ofEpochMilli(doc.getDate("datetime").getTime()),
+//                            TimeZone.getDefault().toZoneId());
+                    LocalDateTime ldt = doc.getDate("datetime").toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
+                    Log.d(TAG, ldt.toString());
+                    /*
+                    String reason = (String) doc.getData().get("reason");
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MyVibesActivity.java]: Remove these comments pls

Comment (jacobwong98) [reply app/src/main/java/com/example/vybe/MyVibesActivity.java]: Removed
