### PR TITLE
79.add mood event

### LINKED ISSUE #79: Add Mood Event
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: 01.01.01, 02.01.01, 04.01.0.1

[//]: # (Please Add labels for type of issue)

Description: As a participant, I want to add mood events that contain the current date and time, a required emotional state, and optional brief textual explanation/reason and social situation, so I can look through past mood events as well as so I can view the specific details of my moods from those events. 

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 5

Related Issues: Depends on #63 being closed

Task List

- [x] Create Adding Mood/Vibe Event Activity and corresponding XML file to Project (Refactor/get rid of CUDActivity currently found in Code Base)
- [x] All Vibe Event attributes are Strings (temporarily as placeholders)
- [ ] Description of possible UI Test Case (i.e. Comment below on how adding a Vibe Event works, and how are we supposed to know it works? - Could just reference something previous lab).
- [ ] Mood Event Description is limited to 20 characters (Done in XML file)
- [x] Dropdown selector works for Social Situation (see Issue #41)
- [x] Dropdown selector works for Emotional State (Vibe) *
- [ ] Documentation (UML, Storyboard, Mockups, Wiki)

Notes:
- This issue invalidates issues #32, #34, #39, #47, and potentially #41 as most of the Code Base work done in Issue #63 resulted in much of the work for these issues to be done then. 
- For this issue only, dropdown selector for Vibe should just be a selector containing the names/labels of a Vibe (i.e. Anger, Sad, Surprise, etc.)

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### PR DESCRIPTION
**Pull request by gatilogo**
[//]: # (These are comments and are used for reference and will not show up in the PR)

# Description

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)
Refer to issue #79 

[//]: # (automatically closes given issue number)
Closes #79  

# Proof of Concept

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

# Checklist

[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is properly commented
- [x] Code changes generate no new warnings
- [ ] ~~Explained Testing Strategy~~

### CODE REVIEW

File: app/src/main/java/com/example/vybe/AddVibeActivity.java [hunk 1]
```diff
@@ -0,0 +1,151 @@
...
+        datetimeField = findViewById(R.id.date_time_edit_text);
+        reasonField = findViewById(R.id.reason_edit_text);
+        socialSituationDropdown = findViewById(R.id.social_situation_dropdown);
+        addBtn = findViewById(R.id.add_btn);
+        outputBox = findViewById(R.id.textView);
+
+        newVibeEvent = new VibeEvent();
+
+        // --- Vibes Dropdown ---
+        String[] vibes = new String[]{"Select a vibe", "Happy", "Sad", "Spicy"};
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddVibeActivity.java]: Please have the correct list of vibes here

File: app/src/main/java/com/example/vybe/AddVibeActivity.java [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+        vibeDropdown = findViewById(R.id.vibe_dropdown);
+        datetimeField = findViewById(R.id.date_time_edit_text);
+        reasonField = findViewById(R.id.reason_edit_text);
+        socialSituationDropdown = findViewById(R.id.social_situation_dropdown);
+        addBtn = findViewById(R.id.add_btn);
+        outputBox = findViewById(R.id.textView);
+
+        newVibeEvent = new VibeEvent();
+
+        // --- Vibes Dropdown ---
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddVibeActivity.java]: can we stub out the dropdown functionality for later?

File: app/src/main/java/com/example/vybe/AddVibeActivity.java [hunk 3]
```diff
@@ -0,0 +1,151 @@
...
+                int currMonth = c.get(Calendar.MONTH);
+                int currDay = c.get(Calendar.DAY_OF_MONTH);
+
+                DatePickerDialog dpd = new DatePickerDialog(AddVibeActivity.this, new DatePickerDialog.OnDateSetListener() {
+                    @Override
+                    public void onDateSet(DatePicker datePicker, int year, int month, int day) {
+                        month += 1; // since indexing starts at 0
+                        String dateString = year + "-" + month + "-" + day;
+                        newVibeEvent.setDateTime(LocalDateTime.of(year, month, day, 0, 0));
+//                        int[] selectedTime = new int[2];
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddVibeActivity.java]: remove excess comments please
