### PR TITLE
update unit tests and apply mock dependency fix in gradle

### LINKED ISSUE #169: Look into and discuss 'mock dependency' problem
[//]: # (These are comments and are used for reference and will not show up in the PR)

[//]: # (Please Add labels for type of issue)

Description: When testing VibeEvent, I ran into the following error when trying to test the `getDateTimeString()` method:

Capture

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)
We can either follow the reccomended instructions of modifying the gradle file found [here](http://tools.android.com/tech-docs/unit-testing-support#TOC-Method-...-not-mocked.-), or we can find another way to test the method. I want to hear people's thoughts

Story Points:1

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### PR DESCRIPTION
**Pull request by TheBroMoe**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description: Fixes the mock dependency problem being faced in the issue closed below

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)
* Unit tests are updated to properly test to verify a vibe's date in a vibe event object
* Updated apps gradle file to have `testOptions`
* Ran the app and all tests and had no issues

[//]: # (automatically closes given issue number)
Closes #169 

Proof of Concept
good

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

Checklist

[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is **properly commented**
- [x] Code changes generate no new warnings
- [x] Testing (Unit and/or Intent)

### CODE REVIEW

File: app/src/test/java/com/example/vybe/VibeEventTest.java [hunk 1]
```diff
@@ -58,16 +58,12 @@ public void VibeEventConstructor_FullInit() {
         assertEquals(testVibe.getName(), testVibeEvent.getVibe().getName());
         assertEquals("just really happy", testVibeEvent.getReason());
         assertEquals(testDate.getClass(), testVibeEvent.getDateTime().getClass());
+        assertEquals(formatter.format(testDate), testVibeEvent.getDateTimeString());
         assertEquals("Alone", testVibeEvent.getSocSit().toString());
         assertEquals("", testVibeEvent.getId());
         assertEquals("image", testVibeEvent.getImage());
```
Comment (raysarinas) [inline app/src/test/java/com/example/vybe/VibeEventTest.java]: In the previous empty constructor test, is it now possible to try and `assertNull` on the latitude and longitude now that they are `Double`'s?

Comment (TheBroMoe) [reply app/src/test/java/com/example/vybe/VibeEventTest.java]: Yes it is! I just updated the constructer tests to check for this
