### PR TITLE
155.login activity tests

### LINKED ISSUE #155: Registration and Login/Logout UI Tests
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: 03.01.01

[//]: # (Please Add labels for type of issue)

Description: UI tests for account registration and login/main activities. 

Login Tests:
1. invalid user login
2. invalid user password
3. successful login

Registration Tests: 
1. invalid email - already registered
2. invalid password - too short
3. successful registration - check get redirected to EMPTY my vibes activity. 

Profile Page Tests:
1. login - navigate to profile page activity - check correct text is displayed

Logout Tests:
1. login - navigate to profile page - logout - check redirected to login activity

a test account I made is: espresso@test.ca with password vibecheck

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points:

Related Issues:

[//]: # (Notes:)
[//]: # (- Testing and Documentation tasks should always be assumed, but only need to be explicitly stated if there is something that ~~does not~~ need modification. For example,)
[//]: # (some Issues/Stories may not require one of Unit or Intent tests, and this should be indicated in the task list.)
[//]: # (- Code Reviews are also always assumed to be required, but an issue should only indicate in the description if a review is not required, but someone still shouldn't)
[//]: # (merge their own pull request)

### PR DESCRIPTION
**Pull request by TheBroMoe**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description:  Added tests that test registration, logging in, and going to a user's personal profile. I also deleted AddEditDeleteActivityTest as it will be redone in another issue.

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)

[//]: # (automatically closes given issue number)
Closes #155

Proof of Concept: Tests all pass

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

Checklist
[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is **properly commented**
- [x] Code changes generate no new warnings
- [x] Testing (Unit and/or Intent)
- [x] Documentation (UML, Wiki, etc.)

### CODE REVIEW

File: app/src/androidTest/java/com/example/vybe/LoginActivityTest.java [hunk 1]
```diff
@@ -0,0 +1,134 @@
...
+                .perform(typeText(invalidLoginEmailNoExist), closeSoftKeyboard());
+        onView(withId(R.id.password_edit_text))
+                .perform(typeText(invalidLoginPassword), closeSoftKeyboard());
+        onView(withId(R.id.login_button)).perform(click());
+
+        Thread.sleep(1000);
+
+        /* TODO: try to confirm toast displays message using
+          https://stackoverflow.com/questions/28390574/checking-toast-message-in-android-espresso
+          If time allows */
```
Comment (raysarinas) [inline app/src/androidTest/java/com/example/vybe/LoginActivityTest.java]: Make issue for this sir

File: app/src/main/java/com/example/vybe/MyVibesActivity.java [hunk 2]
```diff
@@ -70,7 +70,6 @@
     private String vibeEventDBPath;
     private boolean allFlag;
     private String filterVibe = "Filter Vibe";
-
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MyVibesActivity.java]: sure
