### PR TITLE
110.refactor everything

### LINKED ISSUE #110: Refactor Everything
[//]: # (These are comments and are used for reference and will not show up in the PR)

User Requirement: N/A

[//]: # (Please Add labels for type of issue)

Description: Refactor code written for part 3. This issue will complete work started in Issue #41 

Note: Also refactor single instance of Vibe Event constructor that does not take any arguments/parameters. Better to have a constructor that sets the current LocalDateTime, instead of how we have it now [here](https://github.com/CMPUT301F19T02/Vybe/blob/b41aa4fb53b23cb35d17dc8edc86d5880ffba9a2/app/src/main/java/com/example/vybe/AddEditVibeActivity.java#L106).

[//]: # (If an issue is a bug or defect, please list steps to be able to reproduce bug and a screenshot of the defect i.e terminal message)

Story Points: 8

### PR DESCRIPTION
**Pull request by raysarinas**
[//]: # (These are comments and are used for reference and will not show up in the PR)

Description: 
A couple notes:
* The `MapFragment` has been changed a lot. The `MapFragment`'s job is only to show the map, its markers and the user's location. So I've changed things with that in mind. 
    * I've added a `OnMapFragmentReadyListener` interface so that any class that uses the `MapFragment` can add markers and set locations without worrying about if the map will be ready
    * When the map is ready, it calls its Activity's `onMapFragmentReady` method
    * I've moved the `addVibeLocations` method to the `MapViewActivity` - it gets the vibeEvents and sets the markers on the map
* Social Situation Enums have been added but are only used in the `SocialSituationFragment`. I wasn't sure if we wanted to add that the `VibeEvent` class or not
* I haven't touched `MyVibesActivity` because I was afraid of breaking things. But I do think it can be improved.
* Changed xml file names to match convention
* The `StringReason_EnterText_Invalid` test still doesn't work and idk why

Thank you Scrum Master for helping me out a lot and for creating this pull request

[//]: # (Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change)

Refer to Issue #110 for information

[//]: # (automatically closes given issue number)
Closes #110  

Proof of Concept

[//]: # (Attach Image of feature added or fix applied and working)
[//]: # (Please provide images of tests passing)

Checklist

[//]: # (Add an x between square brackets to mark item as done)

- [x] Follows style guidelines and is **properly commented**
- [x] Code changes generate no new warnings

### CODE REVIEW

File: app/src/main/java/com/example/vybe/PermissionsController.java [hunk 1]
```diff
@@ -0,0 +1,6 @@
+package com.example.vybe;
+
+public class PermissionsController {
```
Comment (jacobwong98) [inline app/src/main/java/com/example/vybe/PermissionsController.java]: What is this for?

File: app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java [hunk 2]
```diff
@@ -0,0 +1,265 @@
...
+//    }
+//
+//    public void editVibeEvent(VibeEvent vibeEvent) {
+//        if (imageIsSelected) {
+//            uploadImage(imageBitmap, vibeEvent.getId());
+//            vibeEvent.setImage("reasons/" + vibeEvent.getId() + ".jpg");
+//        }
+//        HashMap<String, Object> data = createVibeEventData(vibeEvent);
+//        db.collection("VibeEvent").document(vibeEvent.getId()).set(data);
+//    }
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java]: Can these comments be removed?

File: app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java [hunk 3]
```diff
@@ -0,0 +1,265 @@
...
+        // Get the download URL for Glide
+        imageRef.getDownloadUrl().addOnSuccessListener(new OnSuccessListener<Uri>() {
+            @Override
+            public void onSuccess(Uri uri) {
+                Glide.with(getApplicationContext())
+                        .load(uri) // Load the image
+                        .into(imageView); // Destination to load image into
+            }
+        });
+    }
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java]: Are these functions still going to be moved to a controller class?

**Comment by PranavB6** [comment]
I've updated the description, please have a look

File: app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+    private ArrayAdapter<String> createSocStnAdapter() {
+        List<String> options = SocialSituation.stringValues();
+        options.add("Select a Social Situation");
+
+        return new ArrayAdapter<String>(context, android.R.layout.simple_spinner_dropdown_item, options) {
+            @Override
+            public int getCount() {
+                // don't display last item. It is used as hint.
+                int count = super.getCount();
+                return count > 0 ? count - 1 : count;
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java]: can you comment on what this returns? like it might look weird and confusing to some people

File: app/src/main/java/com/example/vybe/LocationController.java [hunk 5]
```diff
@@ -0,0 +1,28 @@
...
+import android.content.Context;
+import android.content.pm.PackageManager;
+import android.location.Location;
+import android.location.LocationManager;
+import android.widget.Toast;
+
+import androidx.core.content.ContextCompat;
+
+public class LocationController {
+
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/LocationController.java]: Is there anything else from other Location-related classes that can be moved into this controller? Seems kind of pointless to just have one method in here.

File: app/src/main/java/com/example/vybe/MainActivity.java [hunk 6]
```diff
@@ -40,13 +41,19 @@ protected void onCreate(Bundle savedInstanceState) {
...
 
+
         loginButton = findViewById(R.id.login_button);
         signupButton = findViewById(R.id.signup_button);
         emailField = findViewById(R.id.email_edit_text);
         passwordField = findViewById(R.id.password_edit_text);
 
+        emailField.setText("test2@vybe.ca");
+        passwordField.setText("testuser2");
+
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MainActivity.java]: someone remove this before merging to master pls

File: app/src/main/java/com/example/vybe/MapFragment.java [hunk 7]
```diff
@@ -58,8 +54,25 @@
     private MapView mMapView;
     private FirebaseFirestore db = FirebaseFirestore.getInstance();
     private GoogleMap mMap;
-    private VibeEvent vibe;
+    private OnMapFragmentReadyListener onMapFragmentReadyListener;
+
+//    private LocationController locationController;
+
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MapFragment.java]: why is this commented out?

File: app/src/main/java/com/example/vybe/MapViewActivity.java [hunk 8]
```diff
@@ -1,62 +1,71 @@
...
 
 
     @Override
     protected void onCreate(Bundle savedInstanceState) {
         super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_map_view);
-        mapViewFragment = (MapFragment) getSupportFragmentManager().findFragmentById(map_view_fragment);
+        mapFragment = (MapFragment) getSupportFragmentManager().findFragmentById(map_view_fragment);
+        Log.d(TAG, "onCreate: showing map");
+    }
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MapViewActivity.java]: remove log please

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java [hunk 9]
```diff
@@ -0,0 +1,52 @@
+package com.example.vybe.Models;
+
+import androidx.annotation.NonNull;
+
+import java.util.ArrayList;
+
+public enum SocialSituation {
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/Models/SocialSituation.java]: please add comments to this entire file

File: app/src/main/java/com/example/vybe/Models/VibeEvent.java [hunk 10]
```diff
@@ -46,10 +51,10 @@ public VibeEvent() {
...
      * @param image
      *      This is a photograph expressing the reason a vibe event occurred
-     * @param placeID
-     *      This is the ID google API uses to identify places
-     * @param placeName
-     *      This is the name of the place in google's API
+     * @param latitude
+     *      Emmett fill this in
+     * @param longitude
+     *      Emmett fill this in
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/Models/VibeEvent.java]: @EPostill please fill this in I guess

File: app/src/main/java/com/example/vybe/MyVibesActivity.java [hunk 11]
```diff
@@ -114,24 +113,34 @@ public void onSuccess(QuerySnapshot queryDocumentSnapshots) {
...
+
+//                                            LocalDateTime ldt = doc.getDate("datetime").toInstant().atZone(ZoneId.systemDefault()).toLocalDateTime();
+//                                            Log.d(TAG, ldt.toString());
+//                                            String reason = (String) doc.getData().get("reason");
+//                                            String socSit = (String) doc.getData().get("socSit");
+//                                            String id = (String) doc.getData().get("ID");
+//                                            String vibe = (String) doc.getData().get("vibe");
+//                                            String image = (String) doc.getData().get("image");
+//                                            double latitude = (double) doc.getData().get("latitude");
+//                                            double longitude = (double) doc.getData().get("longitude");
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/MyVibesActivity.java]: can we remove excess amounts of commented code unless there is an explanation for it

File: app/src/main/java/com/example/vybe/PermissionsController.java [hunk 12]
```diff
@@ -0,0 +1,6 @@
...
+
+
+}
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/PermissionsController.java]: why do we have this if it's empty

File: app/src/main/java/com/example/vybe/ViewVibeActivity.java [hunk 13]
```diff
@@ -61,38 +62,48 @@ protected void onCreate(Bundle savedInstanceState) {
...
+        String dateFieldText = month + dateTime.format(formatter);
+        dateField.setText(dateFieldText);
+        String reason = vibeEvent.getReason();
+        String socialSituation = vibeEvent.getSocialSituation();
+        // TODO: missing location - do that later once done
+        String reasonImagePath = vibeEvent.getImage();
+
+        if (reasonImagePath != null){
+            loadImageFirebase(reasonImage, reasonImagePath);
+        }
```
Comment (raysarinas) [inline app/src/main/java/com/example/vybe/ViewVibeActivity.java]: I wrote this function but we should keep in mind populating vibe event details is common and done through a bunch of different code, so we could move this to a controller I guess

File: app/src/main/java/com/example/vybe/AddEdit/ImageFieldFragment.java [hunk 14]
```diff
@@ -0,0 +1,81 @@
...
+import static android.app.Activity.RESULT_OK;
+
+public class ImageFieldFragment extends Fragment {
+
+    private static final int GET_FROM_GALLERY = 1000;
+
+    Button pickImageBtn;
+    ImageView imageView;
+    Context context;
+    OnImageSelectedListener onImageSelectedListener;
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/AddEdit/ImageFieldFragment.java]: these should be private

File: app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java (hunk 2 above)
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java]: do we still need this here?

File: .gitignore [hunk 15]
```diff
@@ -18,4 +18,11 @@
...
 # Project files
 .project
+<<<<<<< HEAD
+
+# Eclipse files
+.classpath
+.settings/
+=======
 app/src/main/java/com/example/vybe/util/APIKey.java
+>>>>>>> 1d60f1383bbb9c5e49c7049ab920365a652300c0
```
Comment (TheBroMoe) [inline .gitignore]: I don't think these were ever merged properly

File: app/src/main/java/com/example/vybe/MainActivity.java [hunk 16]
```diff
@@ -40,13 +41,19 @@ protected void onCreate(Bundle savedInstanceState) {
...
         setContentView(R.layout.activity_main);
 
+
         loginButton = findViewById(R.id.login_button);
         signupButton = findViewById(R.id.signup_button);
         emailField = findViewById(R.id.email_edit_text);
         passwordField = findViewById(R.id.password_edit_text);
 
+        emailField.setText("test2@vybe.ca");
+        passwordField.setText("testuser2");
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MainActivity.java]: these should be removed

File: app/src/main/java/com/example/vybe/MainActivity.java [hunk 17]
```diff
@@ -40,13 +41,19 @@ protected void onCreate(Bundle savedInstanceState) {
...
+
         mAuth = FirebaseAuth.getInstance();
 
+//        mAuth.signOut();
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MainActivity.java]: what is this?

File: app/src/main/java/com/example/vybe/MapFragment.java [hunk 18]
```diff
@@ -170,53 +168,47 @@ public void onLowMemory() {
...
+        setCamera(new LatLng(location.getLatitude(), location.getLongitude()));
+    }
+
+    public void addMarker(LatLng latLng, @DrawableRes int drawableRes) {
+        BitmapDescriptor marker = vectorToBitmap(drawableRes);
+        mMap.addMarker(new MarkerOptions().position(latLng).icon(marker));
+    }
+
+    private void setCamera(LatLng latLng) {
+        CameraUpdate cameraUpdate = CameraUpdateFactory.newLatLngZoom(latLng, 15);
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MapFragment.java]: i think the 15 here (and any other hard coded values) can be moved to the constants file but ok

File: app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java [hunk 19]
```diff
@@ -0,0 +1,265 @@
...
+
+        toolbar = findViewById(R.id.add_edit_vibes_toolbar);
+        reasonField = findViewById(R.id.reason_edit_text);
+        addBtn = findViewById(R.id.add_btn);
+        pageTitle = findViewById(R.id.add_edit_vybe_title);
+        pickLocationButton = findViewById(R.id.btn_add_location);
+        vibeImage = findViewById(R.id.vibe_image);
+        imageView = findViewById(R.id.imageView);
+        mapFragment = (MapFragment) getSupportFragmentManager().findFragmentById(R.id.add_edit_map_fragment);
+        socStnFragment = (SocialSituationFieldFragment) getSupportFragmentManager().findFragmentById(R.id.social_situation_field_fragment);
```
Comment (TheBroMoe) [inline app/src/main/java/com/example/vybe/AddEdit/AddEditVibeEventActivity.java]: The indentation appears to be off

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java [hunk 20]
```diff
@@ -0,0 +1,52 @@
...
+    Alone("Alone"),
+    WithAnotherPerson("With one other person"),
+    WithSeveralPeople("With two or several people"),
+    WithCrowd("With a crowd"),
+    Same("Same");
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/Models/SocialSituation.java]: why do we need this?

File: app/src/main/java/com/example/vybe/AddEdit/ImageFieldFragment.java [hunk 21]
```diff
@@ -0,0 +1,81 @@
...
+
+import com.example.vybe.R;
+
+import java.io.IOException;
+
+import static android.app.Activity.RESULT_OK;
+
+public class ImageFieldFragment extends Fragment {
+
+    private static final int GET_FROM_GALLERY = 1000;
```
Comment (TheBroMoe) [inline app/src/main/java/com/example/vybe/AddEdit/ImageFieldFragment.java]: This should be moved to `util/constants.java`

File: app/src/main/java/com/example/vybe/MyVibesAdapter.java [hunk 22]
```diff
@@ -45,30 +50,40 @@ public View getView(int position, @Nullable View convertView, @NonNull ViewGroup
...
 
-        dateField.setText(month + dateTime.format(formatter));
-
-        if (vibeEvent.getVibe() != null) {
-            vibeImage.setImageResource(vibeEvent.getVibe().getEmoticon());
-        } else {
-            vibeImage.setImageResource(R.drawable.ic_no_vibe);
-        }
-
+        // TODO: DO WE WANT TO DISPLAY REASON?
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MyVibesAdapter.java]: my answer would be no, i was going to suggest to remove it since we were having issues with displaying them anyway

File: app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java [hunk 23]
```diff
@@ -0,0 +1,108 @@
...
+        };
+    }
+
+    /**
+     * Set the default Social Situation. If the string doesn't match any of the social situations,
+     * the social situation is not set (it is null aka "Select a Social Situation")
+     * @param socStnDesc
+     */
+    public void setDefaultSocStn(String socStnDesc) {
+        SocialSituation ss = SocialSituation.of(socStnDesc);
```
Comment (TheBroMoe) [inline app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java]: Variables names like this should be elaborated on, eventually, as these can be hard to work with or look up in the future

File: app/src/main/res/layout/activity_add_edit_vibe.xml [hunk 24]
```diff
@@ -101,7 +88,7 @@
                 android:layout_width="wrap_content"
                 android:layout_height="wrap_content" />
 
-<!--            <TextView-->
+            <!--            <TextView-->
```
Comment (gatilogo) [inline app/src/main/res/layout/activity_add_edit_vibe.xml]: can we also remove this?

File: app/src/main/java/com/example/vybe/MyVibesAdapter.java [hunk 25]
```diff
@@ -27,6 +29,9 @@
     private Context context;
     private ArrayList<VibeEvent> vibeEventList;
     private int resource;
+    TextView dateField;
+    TextView reasonField;
+    ImageView vibeImage;
```
Comment (gatilogo) [inline app/src/main/java/com/example/vybe/MyVibesAdapter.java]: these should be private as well

File: app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java (hunk 23 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/AddEdit/SocialSituationFieldFragment.java]: It had a really small scope so I didn't care too much about it, but you're right, it should be named better

File: app/src/main/java/com/example/vybe/MainActivity.java (hunk 16 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MainActivity.java]: Done!

File: app/src/main/java/com/example/vybe/MainActivity.java (hunk 17 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MainActivity.java]: Once you sign in, it remembers you. So you have to manually tell it to sign out. But I'll get rid of the comment

File: app/src/main/java/com/example/vybe/MapFragment.java (hunk 7 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MapFragment.java]: The `getUserLocation()` method in `LocationController` is now static so we no longer need instances of LocationController

Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MapFragment.java]: I'll get rid of the comment tho

File: app/src/main/java/com/example/vybe/MapFragment.java (hunk 18 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MapFragment.java]: Aii

File: app/src/main/java/com/example/vybe/MapViewActivity.java (hunk 8 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MapViewActivity.java]: ok

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java (hunk 9 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/Models/SocialSituation.java]: LMAO

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java (hunk 20 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/Models/SocialSituation.java]: It's supposed to make it easier to work with SocialSituations

File: app/src/main/java/com/example/vybe/MyVibesAdapter.java (hunk 25 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/MyVibesAdapter.java]: Kk

File: app/src/main/java/com/example/vybe/ViewVibeActivity.java (hunk 13 above)
Comment (PranavB6) [reply app/src/main/java/com/example/vybe/ViewVibeActivity.java]: Kk

File: app/src/main/res/layout/activity_add_edit_vibe.xml (hunk 24 above)
Comment (PranavB6) [reply app/src/main/res/layout/activity_add_edit_vibe.xml]: yee

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java (hunk 20 above)
Comment (gatilogo) [reply app/src/main/java/com/example/vybe/Models/SocialSituation.java]: sorry, I meant to ask if we need the option "same"

File: app/src/androidTest/java/com/example/vybe/AddEditVibeEventActivityTest.java [hunk 26]
```diff
@@ -108,15 +107,21 @@ public void StringReason_EnterText_Valid(){
...
         solo.clickOnButton("Save");
 
-        assertEquals("Expecting an error", "Max 3 words allowed",
+        // Validate the text on the TextView
+        assertEquals("Text should be the field value", "as df ga sd",
+                (editText.getText().toString()));
+
+        assertEquals("Expecting an error", new String("Max 3 words allowed"),
                 (editText.getError().toString()));
     }
```
[the remark this answers is not in the document]
Comment (TheBroMoe) [reply app/src/androidTest/java/com/example/vybe/AddEditVibeEventActivityTest.java]: If the actual activity screen is able to produce the desired result (i.e entering more than 3 words in the reason field returns an error) and it's just the test failing I can fix it this week

File: app/src/main/java/com/example/vybe/Models/SocialSituation.java (hunk 20 above)
Comment (raysarinas) [reply app/src/main/java/com/example/vybe/Models/SocialSituation.java]: same

**Comment by raysarinas** [comment]
> I've integrated you guy's comments into the code

Looks good to me, unless anyone has more problems with what Pranav has changed, lemme know because I do intend on merging this PR tonight. If there is anything anyone wants to have refactored, just make a new issue for it since this issue has been blocking us from being more productive
